---
title: "annotations - rpca"
author: "Kimberly Olney, PhD"
date: "July/31/2025"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
setwd("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
```

# Libraris, paths, colors
```{r echo=FALSE, message=FALSE}
#detach("package:RSpectra", unload = TRUE)
source(here::here("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/", "file_paths_and_colours.R"))
projectID <- "CWOW_cellbender_RPCAIntegration"
color.panel <- dittoColors()
```

# Read in object
```{r read_object}
# read object
dataObject  <- readRDS(paste0("../rObjects/",projectID,".rds"))
```

# sample order
```{r}
# Remove sample
metadata <- subset(metadata, Sample_ID != "LBD_AS_F4") # This sample had a low number of nuclei post filtering 
metadata$sampleID <- factor(metadata$Sample_ID, levels = c(metadata$Sample_ID)) # keep sample order 
samples <- metadata$sampleID 
sex_order <- factor(metadata$sex_inferred, levels = unique(metadata$sex_inferred))
disease_order <- factor(metadata$TYPE, levels = c("CONTROL", "AD_AT", "LBD_S", "LBD_AS", "LBD_ATS")) # The order in which to display the groups

# obtaining the sample ID from the fastq naming
metadata <- metadata %>%
  mutate(sampleID = gsub(".*_(\\d+)_.*_(BR_Nuclei).*", "\\2_\\1", Lane.Name))
samples <- metadata$sampleID 

# Order the sampleID by disease group, so when plotting the samples are ordered by disease group 
# sampleID with disease_order
order <- metadata %>%
  arrange(disease_order) %>%
  dplyr::select(TYPE, sampleID, Sample_ID)
#write.table(order, "order.txt", quote = F, row.names = F, sep = "\t") # export the order as a text file
samples <- order$sampleID
disease_order <- order$TYPE
sample_order <- factor(order$Sample_ID, levels = order$Sample_ID)
```

# Change indents
```{r change_idents}
barcodes <- colnames(dataObject)
sample <- str_match(barcodes, "(.+)_[ACGT]+")[,2]
table(sample)
unique(sample)
dataObject$sample <- factor(sample) #, levels = samples)
table(dataObject$sample)  # check
Idents(dataObject) <- dataObject$sample
```

Add condition column to metadata
```{r condition_column}
# Match the samples to the dataObject
sample_match <- match(dataObject$sample, samples)

# Sex 
dataObject$sex <- sex_order[sample_match]
table(dataObject$sex) 

# Type
disease_order <- factor(disease_order, levels = c("CONTROL", "AD_AT", "LBD_S", "LBD_AS", "LBD_ATS"))
dataObject$group <- disease_order[sample_match]
table(dataObject$group) 

dataObject$Sample_ID <- sample_order[sample_match]
table(dataObject$Sample_ID) 
```


# Number of nuclie per sample
```{r number_cells}
# Visualize the number of cell counts per sample
data <- as.data.frame(table(dataObject$Sample_ID))
colnames(data) <- c("Sample_ID","frequency")

ncells <- ggplot(data, aes(x = Sample_ID, y = frequency, fill = Sample_ID)) + 
  geom_col() +
  theme_classic() +
  geom_text(aes(label = frequency), 
            position=position_dodge(width=0.9), 
            #vjust=-0.25, 
            hjust = -.025,
            angle = 90) +
  #scale_fill_manual(values = sample_colors) + 
  scale_y_continuous(breaks = seq(0,30000, by = 5000), limits = c(0,30000)) +
  ggtitle("Filtered: nuclei per sample") +
  theme(legend.position =  "none") + 
  theme(axis.text.x = element_text(angle = 45, hjust=1))
path <- paste0("../results/nuclei_count/",projectID, 
               "_cells_per_sample_post_QC_and_doublets_removed")
ncells
saveToPDF(paste0(path, ".pdf"), width = 12, height = 5)

# mean cell count 
mean(data$frequency)

# median cell count 
median(data$frequency)
```

# UMAP by group and sample
```{r dimplot1}
dataObject
DimPlot(dataObject,
        group.by = "group", reduction = "integrated.rpca")

DimPlot(dataObject,
        group.by = "Sample_ID", reduction = "integrated.rpca")
```

# Unannotated 
### UMAP
```{r unannotated_umap}
# numerical order 
Idents(dataObject) <- factor(dataObject$seurat_clusters, 
                                     levels = as.character(sort(as.numeric(levels(factor(dataObject$seurat_clusters))))))

levels(Idents(dataObject))

ditto_umap <- dittoDimPlot(object = dataObject,
             size = .2,
             var = "seurat_clusters",
             do.label = TRUE,
             labels.highlight = TRUE)
ditto_umap


path <- paste0("../results/UMAP/unannotated/",projectID,
               "_UMAP_unannotated_pass1_clusters")
ditto_umap
saveToPDF(paste0(path, ".pdf"), width = 12, height = 9)


ditto_umap <- dittoDimPlot(object = dataObject,
             size = .2,
             var = "predicted.subclass",
             do.label = TRUE,
             labels.highlight = TRUE)
ditto_umap


path <- paste0("../results/UMAP/unannotated/",projectID,
               "_UMAP_unannotated_pass1_clusters_azimuth")
ditto_umap
saveToPDF(paste0(path, ".pdf"), width = 12, height = 9)
```

### Nuclei count per cluster
```{r count_per_cluster}
count_per_cluster <- FetchData(dataObject,
                               vars = c("ident", "orig.ident")) %>%
  dplyr::count(ident, orig.ident) %>%
  tidyr::spread(ident, n)
count_per_cluster

count_melt <- reshape2::melt(count_per_cluster)
colnames(count_melt) <- c("ident", "cluster", "number of nuclei")
count_max <- count_melt[which.max(count_melt$`number of nuclei`), ]
count_max_value <- count_max$`number of nuclei`
cellmax <- count_max_value + 15000 # so that the figure doesn't cut off the text
count_bar <- ggplot(count_melt, aes(x = factor(cluster), y = `number of nuclei`, fill = `ident`)) +
  geom_bar(
    stat = "identity",
    colour = "black",
    width = 1,
    position = position_dodge(width = 0.8)
  ) +
  geom_text(
    aes(label = `number of nuclei`),
    position = position_dodge(width = 0.9),
    vjust = -0.25,
    angle = 45,
    hjust = -.01
  ) +
  theme_classic() + 
  #scale_fill_manual(values = sample_colors) +
  ggtitle("Number of nuclei per cluster") +  xlab("cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, cellmax))
count_bar
```

```{r load_markers}
markers <- readRDS(paste0("../rObjects/", projectID,"_markers.rds"))
all.markers.strict <- readRDS(paste0("../rObjects/", projectID,"_markers_log2FC1_q0.01.rds"))
```

# Get markers for each cluster
```{r markers_per_cluster}
# unique clusters variable
unique_clusters <- unique(markers$cluster)

# empty list to store individual cluster data frames
cluster_list <- list()

# loop through each cluster and create a data frame
for (i in unique_clusters) {
  cluster_name <- paste0("cluster", i)
  cluster_data <- all.markers.strict[all.markers.strict$cluster == i, ]
  assign(cluster_name, cluster_data)
  cluster_list[[cluster_name]] <- cluster_data
}
```

## Feature plot
```{r featureplot}
# UMAP showing the expression of select features
umap_feature <-
  FeaturePlot(dataObject,
              reduction = "integrated.rpca",
              features = c("TYROBP", "MOG", "AQP4", "RBFOX3"))
umap_feature

```

# Cluster Annotation

## Cluster
```{r cluster0}
# Number of cells per condition
count_per_cluster[,c(1,2)]
# UMAP with only cluster 0
DimPlot(object = subset(dataObject, seurat_clusters == "40"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = color.panel[1])


DimPlot(object = subset(dataObject, seurat_clusters == "39"), reduction = "integrated.rpca", group.by = c("group"))


VlnPlot(dataObject,
        features = cluster0$gene[1:10],
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
cluster0$gene[1:10]
```


# Assign identities
## Individual 
```{r assign_individual}
dataObject.annotated <- RenameIdents(object = dataObject, 
                               "0" = "oligodendrocyte",
                               "1" = "polydencrocyte",
                               "2" = "astrocyte",
                               "3" = "oligodendrocyte",
                               "4" = "oligodendrocyte",
                               "5" = "oligodendrocyte",
                               "6" = "microglia",
                               "7" = "neuron",
                               "8" = "neuron",
                               "9" = "neuron",
                               "10" = "oligodendrocyte",
                               "11" = "oligodendrocyte", # neuron & oligodendrocyte
                               "12" = "neuron",
                               "13" = "neuron",
                               "14" = "oligodendrocyte",
                               "15" = "neuron",
                               "16" = "astrocyte",
                               "17" = "neuron", 
                               "18" = "astrocyte", # noise, ependyma and endothelial
                               "19" = "neuron",
                               "20" = "neuron",
                               "21" = "neuron",
                               "22" = "neuron",
                               "23" = "neuron",
                               "24" = "neuron", # top hit is endothelial
                               "25" = "neuron",
                               "26" = "oligodendrocyte",
                               "27" = "neuron",
                               "28" = "neuron",
                               "29" = "microglia", # noisy & stringy
                               "30" = "neuron",
                               "31" = "neuron", # sample specific
                               "32" = "mural",
                               "33" = "polydencrocyte", # very stringy
                               "34" = "noise", # both endothelial and neurons
                               "35" = "neuron",
                               "36" = "neuron", 
                               "37" = "neuron",
                               "38" = "polydencrocyte",
                               "39" = "endothelial",# but very stringy 
                               "40" = "neuron", # but very stringy 
                               "41" = "neuron",
                               "42" = "neuron",
                               "43" = "neuron",
                               "44" = "neuron", # but pct express is low
                               "45" = "microglia")
dataObject.annotated$individual_clusters <- factor(Idents(dataObject.annotated))

path <- paste0("../results/UMAP/annotated/",projectID,
               "_UMAP_annotated_pass1")
pdf(paste0(path, ".pdf"), width = 12, height = 9)
UMAP_ind <- dittoDimPlot(object = dataObject.annotated,
             size = 0.5,
             var = "individual_clusters",
             reduction.use = "umap",
             do.label = TRUE,
             labels.highlight = TRUE)
UMAP_ind
dev.off()
```



### Nuclei count per cluster
```{r annotated_counts_individual}
count_per_cluster <- FetchData(dataObject.annotated,
                               vars = c("ident", "orig.ident")) %>%
  dplyr::count(ident, orig.ident) %>%
  tidyr::spread(ident, n)
count_per_cluster

count_melt <- reshape2::melt(count_per_cluster)
colnames(count_melt) <- c("ident", "cluster", "number of nuclei")
count_max <- count_melt[which.max(count_melt$`number of nuclei`), ]
count_max_value <- count_max$`number of nuclei`
cellmax <- count_max_value + 25000 # so that the figure doesn't cut off the text
count_bar <- ggplot(count_melt, aes(x = factor(cluster), y = `number of nuclei`, fill = `cluster`)) +
  geom_bar(
    stat = "identity",
    colour = "black",
    width = 1,
    position = position_dodge(width = 0.8)
  ) +
  geom_text(
    aes(label = `number of nuclei`),
    position = position_dodge(width = 0.9),
    vjust = -0.25,
    angle = 45,
    hjust = -.01
  ) +
  theme_classic() + scale_fill_manual(values = color.panel) +
  ggtitle("Number of nuclei per cluster") +  xlab("cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, cellmax))
count_bar
```

```{r nuclei_count_individual, echo=FALSE}
pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_individual_clusters_nuclei_count_pass1.pdf"
  ),
  width = 6,
  height = 4
)
count_bar
dev.off()
```

### DotPlot
```{r dot_individual}
dot_ind <- DotPlot(dataObject.annotated,
                   features = markers.to.plot, 
                  # split.by = "strain", 
                   cluster.idents = TRUE,
                   dot.scale = 8) + RotatedAxis()
dot_ind
```

```{r save_dot_individual, echo=FALSE}
pdf(
  paste0(
    "../results/dot_plot/",
    projectID,
    "_clusters_DotPlot_annotation_pass1.pdf"
  ),
  width = 14,
  height = 5
)
dot_ind
dev.off()
```


### Relative abundance
```{r relative_cell_type}
relative_abundance <- dataObject.annotated@meta.data %>%
  group_by(individual_clusters, orig.ident) %>%
  dplyr::count() %>%
  group_by(orig.ident) %>%
  dplyr::mutate(percent = 100 * n / sum(n)) %>%
  ungroup()


rel_abun <- ggplot(relative_abundance, aes(x = orig.ident, y = percent, fill = individual_clusters)) +
  geom_col() +
  geom_text(aes(label = paste0(round(percent), "%")), 
            position = position_stack(vjust = 0.5), size = 3, color = "white") +
  scale_fill_manual(values = color.panel) +
  ggtitle("Percentage of cell type") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
rel_abun

pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_clusters_relative_abundance_pass1.pdf"
  ),
  width = 6,
  height = 8
)
rel_abun
dev.off()
```

```{r}
relative_abundance <- dataObject.annotated@meta.data %>%
  group_by(individual_clusters, Sample_ID) %>%
  dplyr::count() %>%
  group_by(Sample_ID) %>%
  dplyr::mutate(percent = 100 * n / sum(n)) %>%
  ungroup()


rel_abun <- ggplot(relative_abundance, aes(x = Sample_ID, y = percent, fill = individual_clusters)) +
  geom_col() +
  geom_text(aes(label = paste0(round(percent), "%")), 
            position = position_stack(vjust = 0.5), size = 3, color = "white") +
  scale_fill_manual(values = color.panel) +
  ggtitle("Percentage of cell type") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
rel_abun

pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_clusters_relative_abundance_Sample_ID_pass1.pdf"
  ),
  width = 13,
  height = 6
)
rel_abun
dev.off()

# Group
relative_abundance <- dataObject.annotated@meta.data %>%
  group_by(individual_clusters, group) %>%
  dplyr::count() %>%
  group_by(group) %>%
  dplyr::mutate(percent = 100 * n / sum(n)) %>%
  ungroup()


rel_abun <- ggplot(relative_abundance, aes(x = group, y = percent, fill = individual_clusters)) +
  geom_col() +
  geom_text(aes(label = paste0(round(percent), "%")), 
            position = position_stack(vjust = 0.5), size = 3, color = "white") +
  scale_fill_manual(values = color.panel) +
  ggtitle("Percentage of cell type") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
rel_abun

pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_clusters_relative_abundance_group_pass1.pdf"
  ),
  width = 8,
  height = 6
)
rel_abun
dev.off()
```

# Save RDS 
```{r save_annotations}
saveRDS(dataObject.annotated, paste0("../rObjects/", projectID, "_annotated_before_recluster.rds"), compress = FALSE)
```



