---
title: "annotations post re-cluster"
author: "Kimberly Olney, PhD"
date: "03/19/2025"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
setwd("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
```

# Libraris, paths, colors
```{r echo=FALSE, message=FALSE}
source(here::here("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/", "file_paths_and_colours.R"))
projectID <- "CWOW_cellbender_RPCAIntegration_clean_SCT"
color.panel <- dittoColors()
```

# Read in object
```{r read_object}
# read object
dataObject <- readRDS(paste0("../rObjects/",projectID,".rds"))

# inspect
dataObject
```

# Number of nuclie per sample
```{r number_cells}
# Visualize the number of cell counts per sample
data <- as.data.frame(table(dataObject$Sample_ID))
colnames(data) <- c("Sample_ID","frequency")

ncells <- ggplot(data, aes(x = Sample_ID, y = frequency, fill = Sample_ID)) + 
  geom_col() +
  theme_classic() +
  geom_text(aes(label = frequency), 
            position=position_dodge(width=0.9), 
            #vjust=-0.25, 
            hjust = -.025,
            angle = 90) +
  #scale_fill_manual(values = sample_colors) + 
  scale_y_continuous(breaks = seq(0,30000, by = 5000), limits = c(0,30000)) +
  ggtitle("Filtered: nuclei per sample") +
  theme(legend.position =  "none") + 
  theme(axis.text.x = element_text(angle = 45, hjust=1))
path <- paste0("../results/nuclei_count/",projectID, 
               "_cells_per_sample")
ncells
saveToPDF(paste0(path, ".pdf"), width = 12, height = 4)

# mean cell count 
mean(data$frequency)

# median cell count 
median(data$frequency)
```

# UMAP by group and sample
```{r dimplot1}
DimPlot(dataObject,
        group.by = "group", reduction = "integrated.rpca")

DimPlot(dataObject,
        group.by = "Sample_ID", reduction = "integrated.rpca")
```

# Unannotated 
### UMAP
```{r unannotated_umap}
ditto_umap <- dittoDimPlot(object = dataObject,
             var = "rpca_clusters",
             do.label = TRUE,
             labels.highlight = TRUE, reduction = "integrated.rpca")
ditto_umap
pdf(
  paste0(
    "../results/UMAP/unannotated/",
    projectID,
    ".pdf"
  ),width = 10, height = 8)
ditto_umap
dev.off()
```

### Nuclei count per cluster
```{r count_per_cluster}
Idents(dataObject) <- dataObject$rpca_clusters
count_per_cluster <- FetchData(dataObject,
                               vars = c("ident", "orig.ident")) %>%
  dplyr::count(ident, orig.ident) %>%
  tidyr::spread(ident, n)
count_per_cluster

count_melt <- reshape2::melt(count_per_cluster)
colnames(count_melt) <- c("ident", "cluster", "number of nuclei")
count_max <- count_melt[which.max(count_melt$`number of nuclei`), ]
count_max_value <- count_max$`number of nuclei`
cellmax <- count_max_value + 2000 # so that the figure doesn't cut off the text
count_bar <- ggplot(count_melt, aes(x = factor(cluster), y = `number of nuclei`, fill = `ident`)) +
  geom_bar(
    stat = "identity",
    colour = "black",
    width = 1,
    position = position_dodge(width = 0.8)
  ) +
  geom_text(
    aes(label = `number of nuclei`),
    position = position_dodge(width = 0.9),
    vjust = -0.25,
    angle = 45,
    hjust = -.01
  ) +
  theme_classic() + 
  #scale_fill_manual(values = sample_colors) +
  ggtitle("Number of nuclei per cluster") +  xlab("cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, cellmax))
count_bar
```

### Cluster tree
```{r cluster_tree}
dataObject <- BuildClusterTree(
  object = dataObject,
  dims = 1:30,
  reorder = FALSE,
  reorder.numeric = FALSE
)

tree <- dataObject@tools$BuildClusterTree
tree$tip.label <- paste0("Cluster ", tree$tip.label)
nClusters <- length(tree$tip.label)

path <- paste0("../results/tree/",projectID,
               "_UMAP_unannotated")
pdf(paste0(path, ".pdf"), width = 6, height = 10)
tree_graph <- ggtree::ggtree(tree, aes(x, y)) +
  scale_y_reverse() +
  ggtree::geom_tree() +
  ggtree::theme_tree() +
  ggtree::geom_tiplab(offset = 1) +
  ggtree::geom_tippoint(color = color.panel[1:nClusters],
                        shape = 16,
                        size = 5) +
  coord_cartesian(clip = 'off') +
  theme(plot.margin = unit(c(0, 2.5, 0, 0), 'cm'))
tree_graph
dev.off()
```


## Markers per cluster
```{r find_all_markers, eval=FALSE}
dataObject <- PrepSCTFindMarkers(dataObject)
markers <- SeuratWrappers::RunPrestoAll(
  object = dataObject,
  assay = "SCT",
  slot = "counts",
  only.pos = FALSE
)
write.table(markers, 
            paste0("../results/markers/", projectID, "_markers.tsv"),
            quote = FALSE,
            row.names = FALSE)
saveRDS(markers, paste0("../rObjects/", projectID, "_markers.rds"))
markers <- readRDS(paste0("../rObjects/", projectID,"_markers.rds"))

# rearrange to order by cluster & filter to only include log2FC > 1 & FDR < 0.05
 all.markers.strict <- markers %>%
   group_by(cluster) %>%
   dplyr::filter(avg_log2FC > 1 & p_val_adj < 0.05)

saveRDS(all.markers.strict, paste0("../rObjects/", projectID,"_markers_log2FC1_q0.01.rds"))
all.markers.strict <- readRDS(paste0("../rObjects/", projectID,"_markers_log2FC1_q0.01.rds"))
```

```{r load_markers}
markers <- readRDS(paste0("../rObjects/", projectID,"_markers.rds"))
all.markers.strict <- readRDS(paste0("../rObjects/", projectID,"_markers_log2FC1_q0.01.rds"))
```

# Dot plot
```{r dot_plot}
Idents(dataObject) <- factor(dataObject$seurat_clusters, 
                                     levels = as.character(sort(as.numeric(levels(factor(dataObject$seurat_clusters))))))

levels(Idents(dataObject))
dot_ind_celltype <- DotPlot(dataObject,
                            features = markers.to.plot, 
                            cluster.idents = FALSE,
                            dot.scale = 8) + RotatedAxis()
dot_ind_celltype
pdf(
  paste0(
    "../results/dot_plot/",
    projectID,
    ".pdf"
  ),width = 10, height = 14)
dot_ind_celltype
dev.off()
```

# Get markers for each cluster
```{r markers_per_cluster}
# unique clusters variable
unique_clusters <- unique(markers$cluster)

# empty list to store individual cluster data frames
cluster_list <- list()

# loop through each cluster and create a data frame
for (i in unique_clusters) {
  cluster_name <- paste0("cluster", i)
  cluster_data <- all.markers.strict[all.markers.strict$cluster == i, ]
  assign(cluster_name, cluster_data)
  cluster_list[[cluster_name]] <- cluster_data
}
```

## Feature plot
```{r featureplot}
# UMAP showing the expression of select features
umap_feature <-
  FeaturePlot(dataObject,
              reduction = "integrated.rpca",
              features = c("DOCK8", "PLP1", "AQP4", "RBFOX3"))
umap_feature

path <- paste0("../results/UMAP/unannotated/",projectID,
               "_UMAP_unannotated_celltype_markers")
umap_feature
saveToPDF(paste0(path, ".pdf"), width = 12, height = 10)
```
## Cluster investigation
```{r cluster0}
# Number of cells per condition
count_per_cluster[,c(1,2)]
# UMAP with only cluster 0
DimPlot(object = subset(dataObject, seurat_clusters == "0"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = color.panel[1])
VlnPlot(dataObject,
        features = cluster0$gene[1:10],
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
cluster0$gene[1:10]
```

# Assign identities
## Individual 
```{r assign_individual}
dataObject.annotated <- RenameIdents(object = dataObject, 
                               "0" = "opc",
                               "1" = "oligodendrocyte",
                               "2" = "astrocyte",
                               "3" = "oligodendrocyte",
                               "4" = "oligodendrocyte",
                               "5" = "microglia",
                               "6" = "oligodendrocyte",
                               "7" = "oligodendrocyte",
                               "8" = "oligodendrocyte",
                               "9" = "neuron",
                               "10" = "neuron",
                               "11" = "neuron",
                               "12" = "neuron",
                               "13" = "oligodendrocyte",
                               "14" = "interneuron",
                               "15" = "neuron",
                               "16" = "oligodendrocyte",
                               "17" = "astrocyte", 
                               "18" = "interneuron",
                               "19" = "interneuron", 
                               "20" = "neuron",
                               "21" = "interneuron",
                               "22" = "interneuron",
                               "23" = "neuron",
                               "24" = "neuron",
                               "25" = "neuron",
                               "26" = "neuron",
                               "27" = "interneuron",
                               "28" = "interneuron", 
                               "29" = "mural",
                               "30" = "interneuron", 
                               "31" = "interneuron", 
                               "32" = "neuron",
                               "33" = "neuron",
                               "34" = "interneuron",
                               "35" = "oligodendrocyte", 
                               "36" = "endothelial",
                               "37" = "neuron",
                               "38" = "neuron",
                               "39" = "interneuron",
                               "40" = "opc",
                               "41" = "microglia",
                               "42" = "oligodendrocyte")
dataObject.annotated$individual_clusters <- factor(Idents(dataObject.annotated))

path <- paste0("../results/UMAP/annotated/",projectID,
               "_UMAP_annotated")
pdf(paste0(path, ".pdf"), width = 8, height = 7)
UMAP_ind <- dittoDimPlot(object = dataObject.annotated,
             var = "individual_clusters",
             reduction.use = "integrated.rpca",
             do.label = TRUE,
             size = 0.5,
             labels.highlight = TRUE)
UMAP_ind
dev.off()
```

### Nuclei count per cluster
```{r annotated_counts_individual}
count_per_cluster <- FetchData(dataObject.annotated,
                               vars = c("ident", "orig.ident")) %>%
  dplyr::count(ident, orig.ident) %>%
  tidyr::spread(ident, n)
count_per_cluster

count_melt <- reshape2::melt(count_per_cluster)
colnames(count_melt) <- c("ident", "cluster", "number of nuclei")
count_max <- count_melt[which.max(count_melt$`number of nuclei`), ]
count_max_value <- count_max$`number of nuclei`
cellmax <- count_max_value + 25000 # so that the figure doesn't cut off the text
count_bar <- ggplot(count_melt, aes(x = factor(cluster), y = `number of nuclei`, fill = `cluster`)) +
  geom_bar(
    stat = "identity",
    colour = "black",
    width = 1,
    position = position_dodge(width = 0.8)
  ) +
  geom_text(
    aes(label = `number of nuclei`),
    position = position_dodge(width = 0.9),
    vjust = -0.25,
    angle = 45,
    hjust = -.01
  ) +
  theme_classic() + scale_fill_manual(values = color.panel) +
  ggtitle("Number of nuclei per cluster") +  xlab("cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, cellmax))
count_bar
```

```{r nuclei_count_individual, echo=FALSE}
pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_individual_clusters_nuclei_count.pdf"
  ),
  width = 6,
  height = 5
)
count_bar
dev.off()
```

### DotPlot
```{r save_dot_individual, echo=FALSE}
dataObject.annotated$group <- factor(dataObject.annotated$group, levels = c("CONTROL", "AD_AT", "LBD_S", "LBD_AS", "LBD_ATS"))
table(dataObject.annotated$group) 

dot_ind <- DotPlot(dataObject.annotated,
                   features = markers.to.plot, 
                   split.by = "group",
                   cols = c("gray35", "#4682B4", "#B4464B", "gray", "gray65"),
                   cluster.idents = TRUE,
                   dot.scale = 8) + RotatedAxis()


pdf(
  paste0(
    "../results/dot_plot/",
    projectID,
    "_clusters_DotPlot_annotation_by_group.pdf"
  ),
  width = 14,
  height = 12
)
dot_ind
dev.off()
```

### Relative abundance
```{r relative_cell_type}
relative_abundance <- dataObject.annotated@meta.data %>%
  group_by(individual_clusters, orig.ident) %>%
  dplyr::count() %>%
  group_by(orig.ident) %>%
  dplyr::mutate(percent = 100 * n / sum(n)) %>%
  ungroup()


rel_abun <- ggplot(relative_abundance, aes(x = orig.ident, y = percent, fill = individual_clusters)) +
  geom_col() +
  geom_text(aes(label = paste0(round(percent), "%")), 
            position = position_stack(vjust = 0.5), size = 3, color = "white") +
  scale_fill_manual(values = color.panel) +
  ggtitle("Percentage of cell type") +
  theme_bw()
rel_abun

pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_clusters_relative_abundance.pdf"
  ),
  width = 4,
  height = 5
)
rel_abun
dev.off()


relative_abundance <- dataObject.annotated@meta.data %>%
  group_by(individual_clusters, group) %>%
  dplyr::count() %>%
  group_by(group) %>%
  dplyr::mutate(percent = 100 * n / sum(n)) %>%
  ungroup()


rel_abun <- ggplot(relative_abundance, aes(x = group, y = percent, fill = individual_clusters)) +
  geom_col() +
  geom_text(aes(label = paste0(round(percent), "%")), 
            position = position_stack(vjust = 0.5), size = 3, color = "white") +
  scale_fill_manual(values = color.panel) +
  ggtitle("Percentage of cell type") +
  theme_bw() 
rel_abun

pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_clusters_relative_abundance_group.pdf"
  ),
  width = 8,
  height = 5
)
rel_abun
dev.off()


relative_abundance <- dataObject.annotated@meta.data %>%
  group_by(individual_clusters, Sample_ID) %>%
  dplyr::count() %>%
  group_by(Sample_ID) %>%
  dplyr::mutate(percent = 100 * n / sum(n)) %>%
  ungroup()


rel_abun <- ggplot(relative_abundance, aes(x = Sample_ID, y = percent, fill = individual_clusters)) +
  geom_col() +
  geom_text(aes(label = paste0(round(percent), "%")), 
            position = position_stack(vjust = 0.5), size = 3, color = "white") +
  scale_fill_manual(values = color.panel) +
  ggtitle("Percentage of cell type") +
  theme_bw()  +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
rel_abun

pdf(
  paste0(
    "../results/UMAP/annotated/",
    projectID,
    "_clusters_relative_abundance_Sample_ID.pdf"
  ),
  width = 12,
  height = 5
)
rel_abun
dev.off()
```

# Save RDS 
```{r save_annotations}
saveRDS(dataObject.annotated, paste0("../rObjects/", projectID, "_annotation.rds"), compress = FALSE)
```


