---
title: "Sex check"
author: "Kimberly Olney, PhD"
date: "2025-07-28"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = "/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/02_qc/", echo=TRUE, warning=FALSE, message=FALSE)
```

```{r readObject}
source(here::here("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/", "file_paths_and_colours.R"))
projectID <- "CWOW_cellranger"
dataObject <- readRDS(file = paste0("../../rObjects/", projectID, "_filtered.rds"))
```

# QC violins 
```{r violin}
XIST <- VlnPlot(dataObject,
              features = c( "XIST"),
              ncol = 1,
              group.by = 'Sample_ID',
              pt.size = 0.01)  + 
    theme(axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          plot.title = element_text(size = 10, face = "plain"),
          legend.position = "none") 

UTY <- VlnPlot(dataObject,
              features = c( "UTY"),
              ncol = 1,
              group.by = 'Sample_ID',
              pt.size = 0.01)  + 
    theme(axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          plot.title = element_text(size = 10, face = "plain"),
          legend.position = "none") 
```

# Combine all plots 
```{r}
ggsave("../../results/violin/XIST.png", XIST, width = 8.5, height = 3.5)
ggsave("../../results/violin/UTY.png", UTY, width = 8.5, height = 3.5)

XIST_img <- ggdraw() + draw_image("../../results/violin/XIST.png")
UTY_img <- ggdraw() + draw_image("../../results/violin/UTY.png")

row1 <- ggarrange(XIST_img, UTY_img, 
                  ncol = 1, nrow = 2,
                  labels = c("A", "B"), 
                  font.label = list(size = 10))
print(row1)

path <- paste0("../../results/violin/", projectID, "_filtered_sex_check")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 7)
```