---
title: "DESeq2 differential expression"
author: "Kimberly Olney, PhD"
date: "03/10/2025"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
setwd("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
```

# Libraris, paths, colors
```{r echo=FALSE, message=FALSE}
source(here::here("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/", "file_paths_and_colours.R"))
projectID <- "CWOW_cellbender_after_recluster_harm_int_noise_removed_after_annotation"
color.panel <- dittoColors()
```

# Read in object
```{r read_object}
# read object
dataObject <- readRDS(paste0("../rObjects/",projectID,".rds"))
DefaultAssay(object = dataObject) <- "RNA"
dataObject[["RNA"]] <- JoinLayers(dataObject[["RNA"]])
dataObject <- NormalizeData(dataObject)

# inspect
dataObject
Layers(dataObject)
# List of cell types to analyze
cell_types <- c(unique(dataObject$individual_clusters))
```

```{r protein_coding}
genes <- readRDS("../rObjects/annotation.rds")
protein_coding_genes <- subset(genes, gene_type == "protein_coding")
```

# Check 
```{r }
# Group
table(dataObject$group) 
```

# Add metadata variables to object
```{r metadata}
metadata <- metadata %>%
  mutate(sampleID = gsub(".*_(\\d+)_.*_(BR_Nuclei).*", "\\2_\\1", Lane.Name))
samples <- metadata$sampleID 
sample_match <- match(dataObject$sample, samples)

Age_order <- factor(metadata$Age, levels = unique(metadata$Age))
dataObject$Age <- Age_order[sample_match]
table(dataObject$Age) 

Braak.NFT_order <- factor(metadata$Braak.NFT, levels = unique(metadata$Braak.NFT))
dataObject$Braak.NFT <- Braak.NFT_order[sample_match]
table(dataObject$Braak.NFT) 

Thal.amyloid_order <- factor(metadata$Thal.amyloid, levels = unique(metadata$Thal.amyloid))
dataObject$Thal.amyloid <- Thal.amyloid_order[sample_match]
table(dataObject$Thal.amyloid) 

metadata$Cing.LB[is.na(metadata$Cing.LB)] <- 0
Cing.LB_order <- factor(metadata$Cing.LB, levels = unique(metadata$Cing.LB))
dataObject$Cing.LB <- Cing.LB_order[sample_match]
table(dataObject$Cing.LB) 

APOE_order <- factor(metadata$APOE, levels = unique(metadata$APOE))
dataObject$APOE <- APOE_order[sample_match]
table(dataObject$APOE) 
```
# Variance
```{r variance}
cell_types <- c(unique(dataObject$individual_clusters))
# Pseudo-bulk the counts based on sample, group, and cell type
dataObject.pseudo <- AggregateExpression(
    dataObject, 
    assays = "RNA", # DESeq works with raw counts
    features = protein_coding_genes$gene_name,
    return.seurat = TRUE, 
    group.by = c("sample", "group", "individual_clusters", "sex", "percent.mt",
                 "APOE", "Cing.LB", "Thal.amyloid","Braak.NFT", "Age")
)


# Assuming your Seurat object is named 'seurat_object'
expression_matrix <- dataObject[["RNA"]]$counts # or seurat_object[["RNA"]]$data
varmetadata <- data.frame(
  sex = dataObject$sex,
  celltype = dataObject$individual_clusters,
  disease = dataObject$group,
  age = dataObject$Age, 
  APOE = dataObject$APOE,
  Cing.LB = dataObject$Cing.LB,
  Thal.amyloid = dataObject$Thal.amyloid, 
  Braak.NFT = dataObject$Braak.NFT
)

# Construct the formula
formula <- ~ sex + disease + celltype + age + APOE + Cing.LB + Thal.amyloid + Braak.NFT
library(variancePartition)
# Run variancePartition
var_part <- fitExtractVarPartModel(expression_matrix, formula, varmetadata)

# You can then analyze the results, for example:
sortCols( var_part )
varpart_plot <- plotVarPart( sortCols( var_part ) )
pdf(paste0("../results/variancePartition/variance_plot.pdf"), height = 8, width = 10)
dev.off()
```


# PCA post pseudo-bulk 
```{r}
# Step 1: Pseudo-bulk the counts based on sample, group, sex, time, and cell type
dataObject.pseudo <- AggregateExpression(
    dataObject, 
    assays = "RNA", 
    features = protein_coding_genes$gene_name,
    return.seurat = TRUE, 
    group.by = c("sample", "group", "predicted.cluster", "sex", "APOE")
)

# Step 2: Normalize the data
dataObject.pseudo <- NormalizeData(dataObject.pseudo, normalization.method = "LogNormalize", scale.factor = 10000)

# Step 3: Find variable features
dataObject.pseudo <- FindVariableFeatures(dataObject.pseudo, selection.method = "vst", nfeatures = 2000)

# Step 4: Scale the data
dataObject.pseudo <- ScaleData(dataObject.pseudo, features = rownames(dataObject.pseudo))

# Step 5: Run PCA
dataObject.pseudo <- RunPCA(dataObject.pseudo, features = VariableFeatures(object = dataObject.pseudo))

# Step 6: Visualize PCA
#pdf(paste0("../results/pca/DESeq2_psuedobulk_cell_type.pdf"), height = 5, width = 6.5)
DimPlot(dataObject.pseudo, reduction = "pca", group.by = "predicted.cluster", shape.by = "group")
#dev.off()

# Step 7: Extract PC scores and metadata
pc_scores <- as.data.frame(Embeddings(dataObject.pseudo, reduction = "pca")[, 1:10]) # Extract PC1 to PC10
# Step 7: Extract metadata
metadata <- as.data.frame(dataObject.pseudo@meta.data)

# Step 8: Combine PC scores and metadata
combined_data <- cbind(pc_scores, metadata)

library(variancePartition)

# Define the formula for CCA
form_PCA <- ~ 
  group +
  sex +
  individual_clusters +
  PC_1 +
  PC_2 +
  PC_3 +
  PC_4 +
  PC_5 +
  PC_6 +
  PC_7 +
  PC_8 +
  PC_9 +
  PC_10 

# Perform Canonical Correlation Analysis
C <- canCorPairs(form_PCA, combined_data)

# Define a function to compute p-values for correlation
cor.mtest <- function(C, ...) {
    C <- as.matrix(C)
    n <- ncol(C)
    p.mat <- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(C[, i], C[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
    colnames(p.mat) <- rownames(p.mat) <- colnames(C)
    p.mat
}

# Compute p-values for correlation
p.mat <- cor.mtest(C)

# Define colors for the heatmap
col <- colorRampPalette(c("#4477AA", "#77AADD", "#FFFFFF", "#EE9988", "#BB4444"))
library(corrplot)
# Plot correlation matrix using corrplot
corrplot(C, method = "color", col = col(200),  
         type = "upper", order = "hclust", 
         addCoef.col = "black", 
         tl.col = "black", tl.srt = 45, 
         diag = FALSE, col.lim = c(0, 1))

# PCA 
pdf(
  paste0(
    "../results/pca/",
    projectID,
    "_pseduobulk_RNA_logNormalize.pdf"
  ),
  width = 7,
  height = 5
)
DimPlot(dataObject.pseudo, reduction = "pca", group.by = "individual_clusters", shape.by = "group")
dev.off()
```


