---
title: "DESeq2 differential expression"
author: "Kimberly Olney, PhD"
date: "03/10/2025"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
setwd("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
```

# Libraris, paths, colors
```{r echo=FALSE, message=FALSE}
source(here::here("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/", "file_paths_and_colours.R"))
projectID <- "CWOW_cellbender_RPCAIntegration_clean_SCT_annotation"
color.panel <- dittoColors()
```

# Read in object
```{r read_object}
# read object
dataObject <- readRDS(paste0("../rObjects/",projectID,".rds"))
# inspect
dataObject
# List of cell types to analyze
cell_types <- c(unique(dataObject$individual_clusters))
```

```{r protein_coding}
genes <- readRDS("../rObjects/annotation.rds")
protein_coding_genes <- subset(genes, gene_type == "protein_coding")
```

# Check 
```{r }
# Group
table(dataObject$group) 
```

```{r}
Idents(dataObject) <- factor(dataObject$individual_clusters, levels = unique(dataObject$individual_clusters))

levels(Idents(dataObject))
dot_ind_celltype <- DotPlot(dataObject,
                            assay = "SCT", 
                            cols = c("green", "blue", "black"),
                            dot.min = .25, 
                            features = genes_markers, 
                            cluster.idents = FALSE,
                            dot.scale = 8) + RotatedAxis()
dot_ind_celltype

getwd()

pdf(
  paste0(
    "../results/dot_plot/",
    projectID,
    "_annotations.pdf"
  ),width = 10, height = 4)
dot_ind_celltype
dev.off()
```

```{r}
#help(VlnPlot)
VlnPlot(dataObject,
        features = c("ERC2"),
       # stack = TRUE,
       # flip = TRUE,
        #split.by = "individual_clusters", 
        split.by = "group", 
        split.plot = TRUE, 
        pt.size = 0.05)
```

```{r cleanup_rObject}
meta_cols <- names(dataObject@meta.data)
cols_to_remove_indices <- grep("^(pANN|DF\\.classifications)", meta_cols)
cols_to_remove <- meta_cols[cols_to_remove_indices]
dataObject@meta.data <- dataObject@meta.data[, -cols_to_remove_indices, drop = FALSE]

print(paste("Columns removed:", paste(cols_to_remove, collapse = ", ")))
print(paste("New number of metadata columns:", ncol(dataObject@meta.data)))
head(dataObject.PSCT@meta.data) 
```

# Prepare for differential expression
```{r prepare}
dataObject.PSCT <- PrepSCTFindMarkers(dataObject, assay = "SCT", verbose = TRUE)
table(Idents(dataObject.PSCT)) # number of cells per cell type by group

dataObject.PSCT$celltype_group <- paste(dataObject.PSCT$individual_clusters, dataObject.PSCT$group, sep = "_")
Idents(dataObject.PSCT) <- "celltype_group"

genes_pc <- protein_coding_genes$gene_name
#  only protein coding genes
genes_pc_filtered <- intersect(genes_pc, rownames(dataObject.PSCT))

levels(Idents(dataObject.PSCT))

```

# Find makers - differential expression 
```{r}
comparisons <- list(
  c("AD_AT", "CONTROL"),
  c("LBD_S", "CONTROL"),
  c("LBD_AS", "CONTROL"),
  c("LBD_ATS", "CONTROL"),
  c("LBD_S", "AD_AT"),
  c("LBD_AS", "AD_AT"),
  c("LBD_ATS", "AD_AT"), 
  c("LBD_AS", "LBD_S"),
  c("LBD_ATS", "LBD_S"),
  c("LBD_ATS", "LBD_AS")
)

main_output_dir <- "../results/DEGs/"
# Iterate through Cell Types
for (cell_type in cell_types) {
  message(paste("Starting differential expression for cell type:", cell_type))
  
  # Create a subdirectory for the current cell type
  cell_type_dir <- file.path(main_output_dir, cell_type)
  dir.create(cell_type_dir, showWarnings = FALSE)
  
  # Inner Loop: Iterate through Pairwise Comparisons
  for (comp in comparisons) {
    pathology_A <- comp[1]
    pathology_B <- comp[2]
    
    # Construct the full identity labels for FindMarkers
    ident_1_label <- paste0(cell_type, "_", pathology_A)
    ident_2_label <- paste0(cell_type, "_", pathology_B)
    
    message(paste("  Running DE for:", pathology_A, "vs", pathology_B))
    
    de_results <- FindMarkers(
      object = dataObject.PSCT,
      ident.1 = ident_1_label,
      ident.2 = ident_2_label,
      features = genes_pc_filtered,
      logfc.threshold = 0.25,
      test.use = "MAST",
      min.pct = 0.2,
      latent.vars = c("sex_inferred", "Age"), # Crucial for controlling sex/age variance 
      min.cells.group = 100,
      densify = TRUE, # Provides speed benefits for sparse matrices
      verbose = FALSE # Set to FALSE in a loop for cleaner output
    )
    
    de_results$gene <- rownames(de_results)
    
    # Save the results
    filename <- paste0("DEG_", cell_type, "_", pathology_A, "_vs_", pathology_B, ".txt")
    write.table(
      de_results, 
      file.path(cell_type_dir, filename), 
      sep = "\t", 
      quote = FALSE, 
      row.names = FALSE
    )
    message(paste("  --> Saved to:", filename))
  }
}
```



```{r findMakers_DE}
#----------
## DEGs per cell type among the groups
DEGs <- SeuratWrappers::RunPrestoAll(
  object = dataObject.prepSCT,
  features = pcg_filtered, 
  logfc.threshold = 0.25, 
  assay = "SCT",
  slot = "counts",
  only.pos = FALSE,
  test.use = "MAST",
  min.pct = 0.2, # only test genes that are detected in a minimum fraction of min.pct cells in either of the two populations
  latent.vars = c("sex_inferred", "Age"),
  min.cells.group = 100,  # minimum number of cells in one of the groups
  densify = TRUE, # convert the sparse matrix to a dense form before running the DE test. This can provide speedups but might require higher memory
  verbose = TRUE)

saveRDS(DEGs, paste0("../rObjects/", projectID, "_DEGs.rds"))
write.table(DEGs, 
            paste0("../results/DEGs/", projectID, "_DEGs.tsv"),
            quote = FALSE,
            row.names = FALSE)
```

# DESeq all cell type pseudo-bulk
```{r DESeq_all_samples}
output_dir <- "../results/DEGs/DEGs_rpca"
# List of cell types to analyze
# Pseudo-bulk the counts based on sample, group, sex, time, and cell type
dataObject.pseudo <- AggregateExpression(
    dataObject, 
    assays = "SCT", # DESeq works with raw counts
    features = protein_coding_genes$gene_name,
    return.seurat = TRUE, 
    group.by = c("sample", "group", "sex")
)

# Function to calculate pct.1 and pct.2
calculate_percentages <- function(counts, group_labels) {
    percent_expressing <- function(group_counts) {
        apply(group_counts, 1, function(x) sum(x > 0) / length(x))
    }
    pct_list <- lapply(levels(group_labels), function(label) {
        percent_expressing(counts[, group_labels == label])
    })
    pct_df <- do.call(cbind, pct_list)
    colnames(pct_df) <- paste0("percent_", levels(group_labels))
    return(pct_df)
}
Idents(dataObject)
# group comparison with covariates
dataObject.pseudo$allcells.group <- paste(dataObject$group, sep = "_")
Idents(dataObject.pseudo) <- "allcells.group"
pseudo_bulk_counts <- GetAssayData(dataObject.pseudo, layer = "counts")
# Calculate the mean expression for each gene
gene_means <- rowMeans(pseudo_bulk_counts)
gene_means_summary <- summary(gene_means)
# Filter genes with mean expression greater than 1st quartile 
filtered_genes <- names(gene_means[gene_means > gene_means_summary[[2]]])
# Subset the count matrix
filtered_counts <- pseudo_bulk_counts[filtered_genes, ]
pseudo_bulk_meta <- dataObject.pseudo@meta.data

    dds <- DESeqDataSetFromMatrix(
        countData = filtered_counts,
        colData = pseudo_bulk_meta,
        design = ~ group + sex
    )
    dds <- DESeq(dds)
    
#------ LBD(ATS) versus control
    res <- results(dds, contrast = c("group", "LBD-ATS", "CONTROL"))
    
    # Calculate pct.1 and pct.2
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))

    # Combine results
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")], pct_data)
    DEGs$percent_difference <- abs(DEGs$`percent_LBD-ATS` - DEGs$percent_CONTROL) 
    
    group_output_path <- file.path(output_dir, paste0("all_celltypes", "_LBD-ATS_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)

sig_LBD_ATS <- subset(DEGs, padj < 0.05)

#------ LBD(S) versus control
    res <- results(dds, contrast = c("group", "LBD-S", "CONTROL"))
    
    # Calculate pct.1 and pct.2
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))

    # Combine results
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")], pct_data)
    DEGs$percent_difference <- abs(DEGs$`percent_LBD-S` - DEGs$percent_CONTROL) 
    
    group_output_path <- file.path(output_dir, paste0("all_celltypes", "_LBD-S_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)

sig_LBD_S <- subset(DEGs, padj < 0.05)


#------ LBD(AS) versus control
    res <- results(dds, contrast = c("group", "LBD-AS", "CONTROL"))
    
    # Calculate pct.1 and pct.2
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))

    # Combine results
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")], pct_data)
    DEGs$percent_difference <- abs(DEGs$`percent_LBD-AS` - DEGs$percent_CONTROL) 
    
    group_output_path <- file.path(output_dir, paste0("all_celltypes", "_LBD-AS_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)

sig_LBD_AS <- subset(DEGs, padj < 0.05)


#------ AD(AT) versus control
    res <- results(dds, contrast = c("group", "AD-AT", "CONTROL"))
    
    # Calculate pct.1 and pct.2
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))

    # Combine results
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")], pct_data)
    DEGs$percent_difference <- abs(DEGs$`percent_AD-AT` - DEGs$percent_CONTROL) 
    
    group_output_path <- file.path(output_dir, paste0("all_celltypes", "_AD-AT_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)

sig_AD_AT <- subset(DEGs, padj < 0.05)
```

```{r cleanup}
rm(dds, res, DEGs) # clean up 
```

# DESeq within each cell type
```{r setup}
output_dir <- "../results/DEGs/DEGs_rpca"
# List of cell types to analyze
cell_types <- c(unique(dataObject$individual_clusters))
# Pseudo-bulk the counts based on sample, group, and cell type
dataObject.pseudo <- AggregateExpression(
    dataObject, 
    assays = "SCT", # DESeq works with raw counts
    features = protein_coding_genes$gene_name,
    return.seurat = TRUE, 
    group.by = c("sample", "group", "individual_clusters")
)

# Function to calculate pct.1 and pct.2
calculate_percentages <- function(counts, group_labels) {
    percent_expressing <- function(group_counts) {
        apply(group_counts, 1, function(x) sum(x > 0) / length(x))
    }
    pct_list <- lapply(levels(group_labels), function(label) {
        percent_expressing(counts[, group_labels == label])
    })
    pct_df <- do.call(cbind, pct_list)
    colnames(pct_df) <- paste0("percent_", levels(group_labels))
    return(pct_df)
}
dataObject.pseudo$celltype.group <- paste(dataObject.pseudo$individual_clusters, dataObject.pseudo$group, sep = "_")
Idents(dataObject.pseudo) <- "celltype.group"
table(Idents(dataObject.pseudo))
```

#### AD(AT) versus CONTROL
```{r AD_AT_vs_CONTROL}
# Loop through each cell type to perform differential expression analysis for each condition
for (cell_type in cell_types) {
    current_cells <- WhichCells(dataObject.pseudo, idents = paste(cell_type, c("AD-AT", "CONTROL"), sep = "_"))
    pseudo_bulk_counts <- GetAssayData(dataObject.pseudo, slot = "counts")[, current_cells]
    gene_means <- rowMeans(pseudo_bulk_counts)
    gene_means_df <- as.data.frame(gene_means)
    gene_means_df <- subset(gene_means_df, gene_means > 0)
    filtered_genes <- subset(gene_means_df, gene_means > median(gene_means_df$gene_means))
    filtered_counts <- pseudo_bulk_counts[rownames(filtered_genes), ]
    pseudo_bulk_meta <- dataObject.pseudo@meta.data[current_cells, ]
    
    dds <- DESeqDataSetFromMatrix(
        countData = filtered_counts,
        colData = pseudo_bulk_meta,
        design = ~ group
    )
    dds <- DESeq(dds)
    
    res <- results(dds, contrast = c("group", "AD-AT", "CONTROL"))
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")])
    DEGs <- na.omit(DEGs)
    DEGs <- DEGs[order(DEGs$padj), ]
    group_output_path <- file.path(output_dir, paste0(cell_type, "_AD-AT_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)
    rm(dds, res, DEGs) # clean up 
}
```

#### LBD(ATS) versus CONTROL
```{r LBD_ATS_vs_CONTROL}
for (cell_type in cell_types) {
    current_cells <- WhichCells(dataObject.pseudo, idents = paste(cell_type, c("LBD-ATS", "CONTROL"), sep = "_"))
    pseudo_bulk_counts <- GetAssayData(dataObject.pseudo, slot = "counts")[, current_cells]
    gene_means <- rowMeans(pseudo_bulk_counts)
    gene_means_df <- as.data.frame(gene_means)
    gene_means_df <- subset(gene_means_df, gene_means > 0)
    filtered_genes <- subset(gene_means_df, gene_means > median(gene_means_df$gene_means))
    filtered_counts <- pseudo_bulk_counts[rownames(filtered_genes), ]
    pseudo_bulk_meta <- dataObject.pseudo@meta.data[current_cells, ]
    
    dds <- DESeqDataSetFromMatrix(
        countData = filtered_counts,
        colData = pseudo_bulk_meta,
        design = ~ group
    )
    dds <- DESeq(dds)
    
    res <- results(dds, contrast = c("group", "LBD-ATS", "CONTROL"))
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")])
    DEGs <- na.omit(DEGs)
    DEGs <- DEGs[order(DEGs$padj), ]
    group_output_path <- file.path(output_dir, paste0(cell_type, "_LBD-ATS_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)
    rm(dds, res, DEGs) # clean up 
}
```

#### LBD(AS) versus CONTROL
```{r LBD_AS_vs_CONTROL}
for (cell_type in cell_types) {
    current_cells <- WhichCells(dataObject.pseudo, idents = paste(cell_type, c("LBD-AS", "CONTROL"), sep = "_"))
    pseudo_bulk_counts <- GetAssayData(dataObject.pseudo, slot = "counts")[, current_cells]
    gene_means <- rowMeans(pseudo_bulk_counts)
    gene_means_df <- as.data.frame(gene_means)
    gene_means_df <- subset(gene_means_df, gene_means > 0)
    filtered_genes <- subset(gene_means_df, gene_means > median(gene_means_df$gene_means))
    filtered_counts <- pseudo_bulk_counts[rownames(filtered_genes), ]
    pseudo_bulk_meta <- dataObject.pseudo@meta.data[current_cells, ]
    
    dds <- DESeqDataSetFromMatrix(
        countData = filtered_counts,
        colData = pseudo_bulk_meta,
        design = ~ group
    )
    dds <- DESeq(dds)
    
    res <- results(dds, contrast = c("group", "LBD-AS", "CONTROL"))
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")])
    DEGs <- na.omit(DEGs)
    DEGs <- DEGs[order(DEGs$padj), ]
    group_output_path <- file.path(output_dir, paste0(cell_type, "_LBD-AS_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)
    rm(dds, res, DEGs) # clean up 
}
```


#### LBD(S) versus CONTROL
```{r LBD_S_vs_CONTROL}
for (cell_type in cell_types) {
    current_cells <- WhichCells(dataObject.pseudo, idents = paste(cell_type, c("LBD-S", "CONTROL"), sep = "_"))
    pseudo_bulk_counts <- GetAssayData(dataObject.pseudo, slot = "counts")[, current_cells]
    gene_means <- rowMeans(pseudo_bulk_counts)
    gene_means_df <- as.data.frame(gene_means)
    gene_means_df <- subset(gene_means_df, gene_means > 0)
    filtered_genes <- subset(gene_means_df, gene_means > median(gene_means_df$gene_means))
    filtered_counts <- pseudo_bulk_counts[rownames(filtered_genes), ]
    pseudo_bulk_meta <- dataObject.pseudo@meta.data[current_cells, ]
    
    dds <- DESeqDataSetFromMatrix(
        countData = filtered_counts,
        colData = pseudo_bulk_meta,
        design = ~ group
    )
    dds <- DESeq(dds)
    
    res <- results(dds, contrast = c("group", "LBD-S", "CONTROL"))
    pct_data <- calculate_percentages(filtered_counts, factor(pseudo_bulk_meta$group))
    res$gene <- rownames(res)
    res <- as.data.frame(res)
    DEGs <- cbind(res[, c("gene", "baseMean", "log2FoldChange","lfcSE", "stat", "pvalue", "padj")])
    DEGs <- na.omit(DEGs)
    DEGs <- DEGs[order(DEGs$padj), ]
    group_output_path <- file.path(output_dir, paste0(cell_type, "_LBD-S_vs_CONTROL_comparison_pseudobulk.txt"))
    write.table(DEGs, file = group_output_path, sep = "\t", quote = FALSE, row.names = FALSE)
    rm(dds, res, DEGs) # clean up 
}
```

# PCA post pseudo-bulk 
```{r}
# # Step 1: Pseudo-bulk the counts based on sample, group, sex, time, and cell type
# dataObject.pseudo <- AggregateExpression(
#     dataObject, 
#     assays = "RNA", 
#     features = protein_coding_genes$gene_name,
#     return.seurat = TRUE, 
#     group.by = c("SampleID", "group", "individual_clusters")
# )
# 
# # Step 2: Normalize the data
# dataObject.pseudo <- NormalizeData(dataObject.pseudo, normalization.method = "LogNormalize", scale.factor = 10000)
# 
# # Step 3: Find variable features
dataObject.pseudo <- FindVariableFeatures(dataObject.pseudo, selection.method = "vst", nfeatures = 2000)
# 
# # Step 4: Scale the data
# dataObject.pseudo <- ScaleData(dataObject.pseudo, features = rownames(dataObject.pseudo))

# Step 5: Run PCA
dataObject.pseudo <- RunPCA(dataObject.pseudo, features = VariableFeatures(object = dataObject.pseudo))

# Step 6: Visualize PCA
DimPlot(dataObject.pseudo, reduction = "pca", label = TRUE) + NoLegend()

pdf(paste0("../results/pca/", projectID, "DESeq2_psuedobulk_cell_type.pdf"), height = 5, width = 6.5)
DimPlot(dataObject.pseudo, reduction = "pca", group.by = "individual_clusters")
dev.off()

# Step 7: Extract PC scores and metadata
pc_scores <- as.data.frame(Embeddings(dataObject.pseudo, reduction = "pca")[, 1:10]) # Extract PC1 to PC10
# Step 7: Extract metadata
metadata <- as.data.frame(dataObject.pseudo@meta.data)

# Step 8: Combine PC scores and metadata
combined_data <- cbind(pc_scores, metadata)

library(variancePartition)

# Define the formula for CCA
form_PCA <- ~ 
  group +
  individual_clusters +
  PC_1 +
  PC_2 +
  PC_3 +
  PC_4 +
  PC_5 +
  PC_6 +
  PC_7 +
  PC_8 +
  PC_9 +
  PC_10 

# Perform Canonical Correlation Analysis
C <- canCorPairs(form_PCA, combined_data)

# Define a function to compute p-values for correlation
cor.mtest <- function(C, ...) {
    C <- as.matrix(C)
    n <- ncol(C)
    p.mat <- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(C[, i], C[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
    colnames(p.mat) <- rownames(p.mat) <- colnames(C)
    p.mat
}

# Compute p-values for correlation
p.mat <- cor.mtest(C)

# Define colors for the heatmap
col <- colorRampPalette(c("#4477AA", "#77AADD", "#FFFFFF", "#EE9988", "#BB4444"))
library(corrplot)
# Plot correlation matrix using corrplot
corrplot(C, method = "color", col = col(200),  
         type = "upper", order = "hclust", 
         addCoef.col = "black", 
         tl.col = "black", tl.srt = 45, 
         diag = FALSE, col.lim = c(0, 1))

# PCA 
pdf(
  paste0(
    "../results/pca/",
    projectID,
    "_pseduobulk_RNA_logNormalize.pdf"
  ),
  width = 7,
  height = 5
)
DimPlot(dataObject.pseudo, reduction = "pca", group.by = "individual_clusters", shape.by = "group")
dev.off()

pdf(
  paste0(
    "../results/pca/",
    projectID,
    "_pseduobulk_RNA_logNormalize.pdf"
  ),
  width = 7,
  height = 5
)
DimPlot(dataObject.pseudo, reduction = "pca", group.by = "individual_clusters", shape.by = "group")
dev.off()
```


