---
title: "shiny"
author: "Kimberly Olney, PhD"
date: "March 2025"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
setwd("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/")
```

# Libraris, paths, colors
```{r echo=FALSE, message=FALSE}
source(here::here("/tgen_labs/jfryer/kolney/LBD_CWOW/LBD_snRNA/scripts/", "file_paths_and_colours.R"))
projectID <- "CWOW_cellbender_after_recluster_harm_int_noise_removed_after_annotation"
color.panel <- dittoColors()
```

# Libraries & paths
```{r libraries_variables}
library(ggdendro)
#library(reticulate, lib.loc = "/usr/local/lib/R/site-library")
library(ShinyCell)
```

# Read RDS 
```{r read_pbj}
dataObject.annotated <- readRDS(paste0("../rObjects/",projectID,".rds"))
# inspect 
dataObject.annotated
DefaultAssay(dataObject.annotated) <- "RNA"
Layers(dataObject.annotated)
dataObject.annotated[["RNA"]] <- JoinLayers(dataObject.annotated[["RNA"]])
Layers(dataObject.annotated)
dataObject.annotated <- NormalizeData(dataObject.annotated)
```

```{r reorder_metadata}
metadata <- colnames(dataObject.annotated@meta.data)
df <- as.data.frame(metadata)
metadata <- metadata[c(110,1:7, 14, 104)]
sc.config <- createConfig(obj = dataObject.annotated, meta.to.include = metadata)
```

# Output directory
```{r warning=FALSE}
makeShinyApp(obj = dataObject.annotated,
             scConf = sc.config, 
             gene.mapping = TRUE,
             shiny.dir = paste0("../shiny_apps/LBD_CWOW_snRNAseq"),
             shiny.title = paste0("LBD CWOW"))
```