---
title: "metadata checks"
author: "Kimberly Olney, Ph.D"
date: "2024-12-10"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

Merge tgen seq info with metadata for matching samples to the fastq files 

# Setup
```{r setup, message=FALSE, warning=FALSE, tidy=TRUE}
knitr::opts_knit$set(root.dir = ".")
```

# User defined variables
sourcing file_paths_and_colours will load the libraries and user defined variables for colors of the graphs
```{r set_variables, message=FALSE, warning=FALSE, tidy=TRUE}
#source(here::here("bulkRNA/scripts/R", "file_paths_and_colours.R"))
library("ggpubr")
library(dplyr)
```

# Read in data
```{r data}
meta <- read.delim("../metadata/metadata.txt")
seq_info <- read.delim("../metadata/LBD_snRNAseq_info.txt")
NPID_sampleID <- read.delim("../metadata/NPID_sampleID.txt")

# merge
seq_NPID <- merge(seq_info, NPID_sampleID, by = "Sample_ID")
seq_meta <- merge(seq_NPID, meta, by = "NPID")

setdiff(seq_NPID$NPID, seq_meta$NPID)

# Keep only unique entries based on the 'id' column
metadata <- seq_meta %>% distinct(NPID, .keep_all = TRUE)
write.table(metadata, "../metadata/metadata_seq_info.txt", sep = "\t", quote = FALSE, row.names = FALSE)
```

# Total percent male

```{r percent_male}
total_sex_percent <- meta %>% 
  group_by(sex_inferred) %>%
  dplyr::count() %>% 
  ungroup(sex_inferred) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))
```

# PMI & RIN
```{r}
saveToPDF <- function(...) {
  d = dev.copy(pdf, ...)
  dev.off(d)
}
ggscatter(meta, x = "PMI", y = "RIN", 
          add = "reg.line", conf.int = FALSE, 
          cor.coeff.args = list(label.x = 20, label.y = 7.5),
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "PMI", ylab = "RIN"
          )
path <- paste0("../results/clinical/PMI_RIN")
saveToPDF(paste0(path, ".pdf"), width = 6, height = 4)

median(na.omit(metadata$RIN))
```

